---
controllers:
  controller_FR:
    controller_address: "/dev/ardu1"
  #controller_FZ:
  #  controller_address: "/dev/ardu1"

# encoders:
#   encoder_FRF:
#     controller: "controller_FZ"
#     index: 1
#     linearization_offset: 13
#     linearization_coeffs: [30,0,9,48,113,172,200,188,150,96,83,62,84,118,97,63]

motors:
  #motor_FRF:
  #  controller: "controller_FR"
  #  index: 0
  #  sensor_index: 0
  #  gear_ratio_inv: 9
  #motor_FRR:
  #  controller: "controller_FR"
  #  index: 1
  #  sensor_index: 1
  #  gear_ratio_inv: 9
  motor_FRF:
    linearization_offset: 8
    linearization_coeffs: [23, 12, 21, 27, 21, 22, 31, 25, 17,  7,  6,  9,  5,  0,  9, 16]
    controller: "controller_FR"
    index: 0
    electric_zero_offset: 526
    encoder_direction: 1
    gear_ratio_inv: 9

legs:
  leg_FR:
    motor_F: "motor_FRF"
    motor_B: "motor_FRR"
    motor_Z: "motor_FRZ"
    theta_p: 0.15
    theta_i: 0.20
    theta_d: 0.0
    gamma_p: 0.15
    gamma_i: 0.20
    gamma_d: 0.0
    z_p: 0.15
    z_i: 0.20
    z_d: 0.0