---
controllers:
  controller_FR:
    controller_address: "/dev/ardu2"
  controller_FL:
    controller_address: "/dev/ardu3"
  controller_FZ:
    controller_address: "/dev/ardu1"
  controller_BZ:
    controller_address: "/dev/ardu4"
  controller_BR:
    controller_address: "/dev/ardu5"
  controller_BL:
    controller_address: "/dev/ardu6"
  

# encoders:
#   encoder_FRF:
#     controller: "controller_FZ"
#     index: 1
#     linearization_offset: 13
#     linearization_coeffs: [30,0,9,48,113,172,200,188,150,96,83,62,84,118,97,63]

motors:
  motor_FRI:
    # linearization_offset: 13
    # linearization_coeffs: [30,0,9,48,113,172,200,188,150,96,83,62,84,118,97,63]
    linearization_offset: 0
    linearization_coeffs: [21,5,19,53,10,156,185,178,156,110,99,69,79,103,81,51]
    controller: "controller_FR"
    index: 0
    electric_zero_offset: 230
    encoder_direction: 1
    gear_ratio_inv: 9
    swap_wires: 0
  motor_FRO:
    linearization_offset: 0
    linearization_coeffs: [31,41,50,52,44,44,51,50,47,46,43,45,25,14,19,26]
    # linearization_offset: 0
    # linearization_coeffs: [25,34,45,44,44,32,28,33,33,27,37,48,23,16,16,19]
    controller: "controller_FR"
    index: 1
    electric_zero_offset: 203
    encoder_direction: 1
    gear_ratio_inv: 9
    swap_wires: 0

  motor_FLI:
    # linearization_offset: 28
    # linearization_coeffs: [42, 37, 31, 29, 9, 9, 21, 22, 32, 29, 17, 10, 9, 0, 20, 30]
    linearization_offset: 0
    linearization_coeffs: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    controller: "controller_FL"
    index: 0
    electric_zero_offset: 240
    encoder_direction: 1
    gear_ratio_inv: 9
    swap_wires: 0
  motor_FLO:
    linearization_offset: 0
    linearization_coeffs: [55, 48, 44, 49, 52, 56, 63, 64, 65, 53, 53, 58, 63, 59, 66, 62]
    # linearization_offset: 0
    # linearization_coeffs: [25,34,45,44,44,32,28,33,33,27,37,48,23,16,16,19]
    controller: "controller_FL"
    index: 1
    electric_zero_offset: 106
    encoder_direction: 1
    gear_ratio_inv: 9
    swap_wires: 1

  motor_FRZ:
    # linearization_offset: 8
    # linearization_coeffs: [23, 12, 21, 27, 21, 22, 31, 25, 17,  7,  6,  9,  5,  0,  9, 16]
    linearization_offset: 0
    linearization_coeffs: [26,27,24,29,39,40,44,36,27,19,22,25,36,46,50,39]
    controller: "controller_FZ"
    index: 0  
    electric_zero_offset: 573
    encoder_direction: 1
    gear_ratio_inv: 9
    swap_wires: 0

  motor_FLZ:
    linearization_offset: 3
    linearization_coeffs: [23, 5, 11, 16, 13, 6, 23, 9, 6, 0, 5, 21, 35, 55, 53, 40]
    controller: "controller_FZ"
    index: 1  
    electric_zero_offset: 435
    encoder_direction: 1
    gear_ratio_inv: 9
    swap_wires: 1

  motor_BRZ:
    linearization_offset: 0
    linearization_coeffs: [11, 8, 13, 15, 24, 15, 23, 25, 25, 22, 15, 32, 16, 6, 13, 12]
    controller: "controller_BZ"
    index: 1
    electric_zero_offset: 551
    encoder_direction: 1
    gear_ratio_inv: 9
    swap_wires: 0

  motor_BLZ:
    #linearization_offset: 3
    #linearization_coeffs: [11, 11, 12, 14, 5, 1, 6, 10, 5, 2, 8, 13, 10, 0, 10, 12]
    linearization_offset: 0
    linearization_coeffs: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    
    controller: "controller_BZ"
    index: 0
    electric_zero_offset: 277
    encoder_direction: 1
    gear_ratio_inv: 9
    swap_wires: 1

  motor_BRO:
    # linearization_offset: 13
    # linearization_coeffs: [30,0,9,48,113,172,200,188,150,96,83,62,84,118,97,63]
    linearization_offset: 0
    linearization_coeffs: [28, 28, 39, 56, 63, 64, 70, 72, 55, 39, 29, 35, 32, 28, 38, 35]
    controller: "controller_BR"
    index: 0
    electric_zero_offset: 39
    encoder_direction: 1
    gear_ratio_inv: 9
    swap_wires: 0

  motor_BRI:
    # linearization_offset: 13
    # linearization_coeffs: [30,0,9,48,113,172,200,188,150,96,83,62,84,118,97,63]
    linearization_offset: 8
    linearization_coeffs: [16, 7, 12, 12, 3, 3, 15, 15, 9, 5, 9, 15, 11, 0, 6, 13]
    controller: "controller_BR"
    index: 1
    electric_zero_offset: 245
    encoder_direction: 1
    gear_ratio_inv: 9
    swap_wires: 1

  motor_BLO:
    # linearization_offset: 13
    # linearization_coeffs: [30,0,9,48,113,172,200,188,150,96,83,62,84,118,97,63]
    linearization_offset: 6
    linearization_coeffs: [32, 21, 11, 17, 6, 0, 0, 9, 2, 3, 11, 23, 29, 24, 43, 40]
    controller: "controller_BL"
    index: 1
    electric_zero_offset: 510
    encoder_direction: 1
    gear_ratio_inv: 9
    swap_wires: 0

  motor_BLI:
    # linearization_offset: 13
    # linearization_coeffs: [30,0,9,48,113,172,200,188,150,96,83,62,84,118,97,63]
    linearization_offset: 35
    linearization_coeffs: [42, 22, 0, 22, 20, 29, 65, 57, 40, 13, 0, 13, 22, 22, 69, 59]
    controller: "controller_BL"
    index: 0
    electric_zero_offset: 229
    encoder_direction: 1
    gear_ratio_inv: 9
    swap_wires: 0


legs:
  leg_FL:
    motor_I: "motor_FLI"
    motor_O: "motor_FLO"
    motor_Z: "motor_FLZ"
    theta_p: 100.0
    theta_i: 50.0
    theta_d: 0.01
    gamma_p: 30.0
    gamma_i: 50.0
    gamma_d: 0.0
    z_p: 50.0
    z_i: 25.0
    z_d: 0
    z_dir: -1.0

    gamma_dir: -1.0
    theta_dir: -1.0
    z_gamma_dir: 1.0
    
    min_z: -0.2
    max_z: 1.4              
    ref_z: 0.412811

    min_gamma: -1.0472 #-60 degrees
    max_gamma: 1.4835  # 85 degrees

    ref_theta: 1.039  # -75 degrees
  leg_FR:
    motor_I: "motor_FRI"
    motor_O: "motor_FRO"
    motor_Z: "motor_FRZ"
    theta_p: 50.0
    theta_i: 25.0
    theta_d: 0.01
    gamma_p: 10.0
    gamma_i: 50.0
    gamma_d: 0.01
    z_p: 30.0
    z_i: 15.0
    z_d: 0
    z_dir: -1.0

    gamma_dir: 1.0
    theta_dir: 1.0
    z_gamma_dir: -1.0
    
    min_z: -0.2
    max_z: 1.4              
    ref_z: 0.5

    min_gamma: -1.4835 #-85 degrees
    max_gamma: 1.0472  # 60 degrees

    ref_theta: -1.039  # -75 degrees
  leg_BR:
    motor_I: "motor_BRI"
    motor_O: "motor_BRO"
    motor_Z: "motor_BRZ"
    theta_p: 100.0
    theta_i: 50.0
    theta_d: 0.01
    gamma_p: 20.0
    gamma_i: 20.0
    gamma_d: 0.01
    z_p: 50.0
    z_i: 25.0
    z_d: 0
    z_dir: -1.0

    gamma_dir: 1.0
    theta_dir: 1.0
    z_gamma_dir: 1.0
    
    min_z: -0.2
    max_z: 1.4              
    ref_z: 0.534678

    min_gamma: -1.4835 #-85 degrees
    max_gamma: 1.0472  # 60 degrees

    ref_theta: -1.039  # -75 degrees
    
    
  leg_BL:
    motor_I: "motor_BLI"
    motor_O: "motor_BLO"
    motor_Z: "motor_BLZ"
    theta_p: 100.0
    theta_i: 50.0
    theta_d: 0.01
    gamma_p: 30.0
    gamma_i: 50.0
    gamma_d: 0.0
    z_p: 50.0
    z_i: 25.0
    z_d: 0
    z_dir: -1.0

    gamma_dir: -1.0
    theta_dir: -1.0
    z_gamma_dir: -1.0
    
    min_z: -0.2
    max_z: 1.4              
    ref_z: 0.0 

    min_gamma: -1.0472 #-60 degrees
    max_gamma: 1.4835  # 85 degrees

    ref_theta: 1.039  # -75 degrees