load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "binary_communication",
    hdrs = ["binary_commands.h", "binary_stream.h"]
)